pipeline {
   agent any

   stages {
      stage('Hello') {
         steps {
            echo 'Hello World'
         }
      }
      stage('hello 2'){
          steps {
              echo 'hello again'
          }
      }
   }
}
